//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionAcademicaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriculas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matriculas()
        {
            this.Notas = new HashSet<Notas>();
        }
    
        public int IdMatricula { get; set; }
        public string CedulaSecretaria { get; set; }
        public string CedulaEstudiante { get; set; }
        public string IdMateria { get; set; }
        public Nullable<byte> RepiteMateria { get; set; }
    
        public virtual Materias Materias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notas> Notas { get; set; }
    }
}
