//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionAcademicaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int IdNotas { get; set; }
        public Nullable<int> IdMatricula { get; set; }
        public Nullable<decimal> Nota1 { get; set; }
        public Nullable<decimal> Nota2 { get; set; }
        public Nullable<decimal> Supletorio { get; set; }
    
        public virtual Matriculas Matriculas { get; set; }
    }
}
